services:
    roanja.rjfilesmanager.repository.rjfile_repository:
        class: Roanja\Rjfilesmanager\Repository\RjfileRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - Roanja\Rjfilesmanager\Entity\Rjfile

    roanja.rjfilesmanager.file.install:
        class: Roanja\Rjfilesmanager\Database\RjfileInstaller
        arguments:
            - '@doctrine.dbal.default_connection'
            - '%database_prefix%'
