admin_rjfilesmanager_list:
  path: /filesmanager/list
  methods: [GET]
  defaults:
    _controller: 'Roanja\Rjfilesmanager\Controller\Admin\RjfileController::indexAction'
    _legacy_controller: AdminFilesManager
    _legacy_link: AdminFilesManager

admin_rjfilesmanager_search:
    path: /filesmanager/list
    methods: [POST]
    defaults:
        _controller: 'Roanja\Rjfilesmanager\Controller\Admin\RjfileController::searchAction'
        _legacy_controller: 'AdminFilesManager'
        _legacy_link: 'AdminFilesManager:search'

admin_rjfilesmanager_create:
  path: /filesmanager/new
  methods: [GET, POST]
  defaults:
    _controller: 'Roanja\Rjfilesmanager\Controller\Admin\RjfileController::createAction'
    _legacy_controller: AdminFilesManager
    # _legacy_link: 'AdminFilesManager:add'

admin_rjfilesmanager_edit:
  path: /filesmanager/edit/{fileId}
  methods: [GET, POST]
  defaults:
    _controller: 'Roanja\Rjfilesmanager\Controller\Admin\RjfileController::editAction'
    _legacy_controller: AdminFilesManager
  requirements:
    fileId: \d+

admin_rjfilesmanager_delete:
  path: /filesmanager/delete/{fileId}
  methods: [DELETE]
  defaults:
    _controller: 'Roanja\Rjfilesmanager\Controller\Admin\RjfileController::deleteAction'
    _legacy_controller: AdminFilesManager
  requirements:
    fileId: \d+

admin_rjfilesmanager_bulk_delete:
    path: /filesmanager/bulkDelete
    methods: [POST]
    defaults:
        _controller: 'Roanja\Rjfilesmanager\Controller\Admin\RjfileController::deleteBulkAction'
        _legacy_controller: 'AdminFilesManager'